name: tmdb
description: "The Flutter app with a lot of films! :)"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter_mobx: ^2.3.0
  mobx: ^2.6.0
  go_router: ^14.0.0
  dio: ^5.4.0
  json_annotation: ^4.8.1
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.0
  path: ^1.8.0
  shared_preferences: ^2.2.0
  flutter_dotenv: ^6.0.0

dev_dependencies:
  build_runner: ^2.4.0
  mobx_codegen: ^2.7.0
  json_serializable: ^6.7.0
  drift_dev: ^2.15.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
